### ISSUE TITLE
`pants tailor --check ::` fails with `Unknown flag --check on global scope` with new PEX distribution mechanism

### ISSUE THREAD

**Issue by huonw** [pantsbuild/scie-pants#249]
**Describe the bug**
In 2.18.0.dev5 and beyond, `pants tailor --check ::` stops working when run under scie-pants 0.9.0 or greater.

This invocation is likely to be widespread, as it is suggested by [docs](https://www.pantsbuild.org/docs/using-pants-in-ci#approach-2-run-over-everything) and [examples](https://github.com/pantsbuild/example-python/blob/751db8be2ed502dba733d8bc1c340064bb9d1995/.github/workflows/pants.yaml#L52). It'd be _really_ good to not break (at least, not without deprecation warnings)

```
Unknown flag --check on global scope
Did you mean --check-only or --tailor-check?
Use `pants help` to get help.
13:19:23.55 [ERROR] Unknown flags --check on global scope


Use --print-stacktrace for more error details and/or -ldebug for more logs. 
See https://www.pantsbuild.org/v2.18/docs/troubleshooting for common issues.
Consider reaching out for help: https://www.pantsbuild.org/v2.18/docs/getting-help
```

Reproducer:

```shell
cd $(mktemp -d)

cat > pants.toml <<EOF
[GLOBAL]
pants_version = "2.18.0.dev5"

backend_packages = ["pants.backend.python"]
EOF

pants tailor --check ::
```

Changing the version to 2.18.0.dev4 passes (no output).

**Pants version**
2.18.0.dev5 to 2.18.0a0 at the time of writing

scie-pants 0.9.0, 0.9.3

**OS**
macOS and Linux

**Additional info**

- I discovered by a "public repo" test run, e.g. https://github.com/pantsbuild/pants/actions/runs/5957288454/job/16159713022
- Changes between those releases: https://github.com/pantsbuild/pants/compare/release_2.18.0.dev4...release_2.18.0.dev5 . ~Nothing leaps out at me. I haven't run a `git bisect` though.~ See first comment: it's the switch to PEX distributions

**Comment by benjyw** [comment]
Great detective work BTW!

**Comment by huonw** [comment]
The `./pants` script behaviour is subtlety different: the argument is passed to `pip install` unquoted, so an empty string expands to no argument at all. https://github.com/pantsbuild/setup/blob/0aaed15895033438f03af88f3714bd804b31993c/pants#L403

Deprecating and removing the `PANTS_SHA` support sounds reasonable. I've sketched something along those lines in https://github.com/pantsbuild/scie-pants/pull/250, which I'll revisit in a while (feel free to take over, though).

I guess it'd also make sense to file a feature request with scie about passing an argument conditionally, which I'll do in a while too.

**Comment by benjyw** [comment]
We can get rid of `PANTS_SHA` support, sure, but this seems like a general issue with scie, no?

**Comment by huonw** [comment]
Filed https://github.com/a-scie/jump/issues/130 for the base scie-jump feature.

To summarise: there's 3 related things that this issue reveals:

1. scie-pants's `PANTS_SHA` support means it needs to sometimes pass an extra arg to pants, and the passing an arg "sometimes" causes issues, but we can work around (and having a work-around isn't so bad if we're planning to remove `PANTS_SHA` support) => #250
2. scie-jump doesn't have support for directly eliding conditional args like this => https://github.com/a-scie/jump/issues/130
3. Tangentially, pants' handling of empty string arguments is a bit peculiar and could be tightened https://github.com/pantsbuild/pants/pull/19666

I'd suggest that #250 seems like the appropriate path forward in the short term, unless scie-jump is improved quickly.

**Comment by thejcannon** [comment]
> The `./pants` script behaviour is subtlety different: the argument is passed to `pip install` unquoted, so an empty string expands to no argument at all. [pantsbuild/setup@`0aaed15`/pants#L403](https://github.com/pantsbuild/setup/blob/0aaed15895033438f03af88f3714bd804b31993c/pants#L403)
> 
> Deprecating and removing the `PANTS_SHA` support sounds reasonable. I've sketched something along those lines in #250, which I'll revisit in a while (feel free to take over, though).
> 
> I guess it'd also make sense to file a feature request with scie about passing an argument conditionally, which I'll do in a while too.

Ah you're right, I think [this](https://github.com/pantsbuild/setup/blob/0aaed15895033438f03af88f3714bd804b31993c/pants#L493C64-L493C78) is the relevant code (although it uses `--python-repos-repos` and not `--python-repos-find-links` hmm)

**Comment by jsirois** [comment]
I think you may have missed the fact that scie-pants already deals with variable argument lists (which scie-jump does not support). See the `pants` vs `pants-debug` commands and the dispatch done by the scie-pants rust binary.
