### ISSUE TITLE
The package crate should re-build `tools/src/scie_pants/pants_release_tags.json`

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/scie-pants#26]
As described here:
https://github.com/pantsbuild/scie-pants/blob/c6258013be227111b37a50b6701b59034b74872d/tools/src/scie_pants/install_pants.py#L101-L106

The `tools/src/scie_pants/pants_release_tags.json` file should be re-generated on every build of scie-pants, or at least for release builds.

**Comment by thejcannon** [comment]
Closing, as this is no longer needed as of `0.9.0` which uses the Pants v2 cheeseshop at https://wheels.pantsbuild.org/simple for all v2 versions.
