### ISSUE TITLE
CI failures when GitHub Actions upgrades its python patch version

### ISSUE THREAD

**Issue by benjyw** [pantsbuild/scie-pants#270]
We cache SCIE_PANTS_DEV_CACHE, which includes venvs that include symlinks into `/opt/hostedtoolcache/` (e.g., 

```
/home/runner/work/scie-pants/scie-pants/.scie_pants_dev_cache/venvs/pants-2.14.1/py39.venv/bin/python3.9 ->
 /opt/hostedtoolcache/Python/3.9.17/x64/bin/python3.9
```

However that symlink target may not exist on a new runner, e.g., when GHA upgrade their "Python 3.9" from 3.9.17 to 3.9.18.

**Comment by thejcannon** [comment]
Once we're done with pants-in-pants hopefully these kinds of issues go away (we'll just have other issues)
