### ISSUE TITLE
Integrate `scie-pants` with pantsbuild/actions.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/scie-pants#31]
Currently, `scie-pants` supports `PANTS_BOOTSTRAP_TOOLS=V scie-pants ...` just like the `./pants` script, but, unlike the `./pants` script, it does not install Pants versions under `~/.cache/pants/setup`. This defeats the current assumptions in https://github.com/pantsbuild/actions:
https://github.com/pantsbuild/actions/blob/d40020ab603a0c2004880f02ececc4d3675bd914/init-pants/action.yaml#L49-L55

**Comment by cognifloyd** [comment]
Where is the cache stored instead?

**Comment by sureshjoshi** [comment]
Per https://github.com/a-scie/jump:

>  It extracts the needed files into a base directory that is traditionally located in the local user cache subdirectory nce (~/.cache/nce on Linux, ~/Library/Caches/nce on macOS and ~\AppData\Local\nce on Windows

**Comment by jsirois** [comment]
The point is though, you should not care. The pantsbuild/actions will learn this by asking the bootstrap tools instead of assuming. It already asks bootstrap tools for other things today.

**Comment by benjyw** [comment]
Done in https://github.com/pantsbuild/actions/pull/16
