### ISSUE TITLE
Create a `get-pants` script and site.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/scie-pants#35]
We'll probably need a `.sh` version and a `.ps1` version that detects the current OS-ARCH and downloads the latest stable scie-pants, adds to $PATH, etc. A gold standard is probably https://rustup.rs/. Critically, it would be good to be able to have the script checked in to Pants repos. This would allow new users of a repo using Pants to run `./get-pants.sh` to get up and running by installing `scie-pants` (as `pants`) on the PATH.

**Comment by benjyw** [comment]
How do we feel about `pantsup` as a name, both in analogy to rustup and for the pun?

**Comment by jsirois** [comment]
This will get checked in to a repo and the actual update command is `SCIE_BOOT=update pants` as documented here:
https://github.com/pantsbuild/scie-pants/blob/2f2b2365c31b45d2fad792810df4855f65b088d2/get-pants.sh#L147-L149

So - I don't really care, but those are your logical / reality constraints on word use.

**Comment by benjyw** [comment]
Hmm, I hadn't thought about checking it in to the repo. That seems weird to me, but maybe? Checking in `./pants` is different in my mind, as you must have that in every repo to do anything. 

E.g., I wouldn't check `rustup` in to the repo.

**Comment by kaos** [comment]
But we could have a recommendation for a one-liner to check-in:
```shell
# get-pants.sh --downloads pantsup.sh and runs it
bash -c "$(curl ...)"
```

**Comment by jsirois** [comment]
@kaos why check in a 1 liner instead of the script? The script is basically a robust 1 liner.

**Comment by jsirois** [comment]
To be super clear (I cannot find the Slack user convo):

I personally would not check in the script. A user, however, pointed out they explicitly liked that there was a checked in script since it made it easy to on-board new devs to the repo with it checked in. They felt "run this script" was easier than separate instructions for how to install the binary 1 time. Taking that concern / perceived benefit seriously, they'd still want this presumably.

**Comment by kaos** [comment]
> @kaos why check in a 1 liner instead of the script? The script is basically a robust 1 liner.

Oh, I'm in no way against checking in the entire script. It was merely a reaction as to an alternative option to Benjy's remark:
> E.g., I wouldn't check rustup in to the repo.

I may recall having expressed similar feelings with having the script checked in and ready to go without further install instructions as the user you are referring to.. :) (also gives some background to my comment for having "something" checked in at least) And, having a one-liner rather than the entire script gives you the benefit (hopefully!? ;) ) of always using the latest version of it.

**Comment by benjyw** [comment]
This has been done, as documented in https://github.com/pantsbuild/pants/pull/18056

If we decide we want to host pantsup.sh elsewhere than static.pantsbuild.org, we can create a new issue for that.

**Comment by jsirois** [comment]
Little quibble, there's cleanup in this repo to do. Killing a script & it's IT.
