### ISSUE TITLE
The 0.10.6 release fixed libcrypt.so.1 dynamic linking but goes unused.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/scie-pants#350]
This is due to 0.10.5 being retroactively released which caused it to be marked latest. Combined with `get-pants.sh` looking for latest in the common use-case: https://github.com/pantsbuild/setup/blob/cf6e4cb6efb0fb0168e0ae624b9b8e568abf0bcf/get-pants.sh#L181

**Comment by jsirois** [comment]
@kaos & @benjyw I still was subscribed to deployement review emails here (now fixed) and got a strange looking deployment review email this am. I initially thought it was 0.10.6 but noticed 0.10.5. The fix is easy, just mark 0.10.6 as latest in the GH UI, which I've just done. This is FYI.

**Comment by benjyw** [comment]
> @kaos & @benjyw I still was subscribed to deployement review emails here (now fixed) and got a strange looking deployment review email this am. I initially thought it was 0.10.6 but noticed 0.10.5. The fix is easy, just mark 0.10.6 as latest in the GH UI, which I've just done. This is FYI.

Thanks for fixing!
