### ISSUE TITLE
Replace CircleCI ARM CI with Pantsbuild's runs-on runners

### ISSUE THREAD

**Issue by huonw** [pantsbuild/scie-pants#422]
The main pants repo now uses "self-hosted" aarch64 linux runners, via runs-on and Pantsbuild's AWS account.

- https://github.com/pantsbuild/pants/pull/21325
- https://github.com/pantsbuild/pants/pull/21329
- https://github.com/pantsbuild/pants/pull/21330
- https://github.com/pantsbuild/pants/pull/21332

We can hopefully do the same here and simplify our configuration by only using Github Actions for CI instead of circle CI too.

We may want to move the pants repo config to be shared: https://runs-on.com/configuration/repo-config/#sharing-configuration-across-repositories

**Comment by jsirois** [comment]
You're probably already aware, but another option is Docker QEMU emulation. I was gunning for $0 when I chose Circle CI and its great for that - I use it for a-scie projects for that reason - but another way to spend $0 at the sacrifice of speed is the emulation.  Examples here: https://github.com/pex-tool/pex/blob/a346870722dfff91cb335e77b6e6c44503e7f733/.github/workflows/gen-scie-platforms.yml#L60-L74

**Comment by huonw** [comment]
Thanks; yeah, I considered it, but decided the incremental cost here is likely to be tiny, compared to spend on these runners in the (already-configured/already-in-use) CI in the main pants repo

(Analysis in https://github.com/pantsbuild/scie-pants/pull/427)
