### ISSUE TITLE
Release CI fails to trigger CircleCI linux aarch64 build

### ISSUE THREAD

**Issue by huonw** [pantsbuild/scie-pants#430]
The 0.12.1 build failed: https://github.com/pantsbuild/scie-pants/actions/runs/12041161791/job/33578047638

`Error: Error: Request failed with status code 403`

also related #422

**Comment by huonw** [comment]
I've marked 0.12.1 as a pre-release, and 0.12.0 as the latest stable release, so because the lack of linux aarch64 binaries was causing issues for anyone running `get-pants.sh` like that (that is, no explicit `--version ...` arg). This got that working again on my system

The pants setup action didn't allow passing that arg until recently: https://github.com/pantsbuild/actions/pull/34

**Comment by martimlobao** [comment]
Not sure if this is an issue since it sounds like the problem is specific to Linux, but the latest version in the Homebrew tap is still 0.12.1: https://github.com/pantsbuild/homebrew-tap/commit/bb3e3bab9b82e9d5ff20cc1ea5b0a99c2a779dd0
