### ISSUE TITLE
Would this be a good candidate for a Homebrew formula?

### ISSUE THREAD

**Issue by sureshjoshi** [pantsbuild/scie-pants#57]
I install most of my Mac tooling via Homebrew, just wondering if someone would know better if this is a candidate for that?

**Comment by jsirois** [comment]
I don't know the answer, but I do hope it's no! There is definitely a tension here. Supporting homebrew - in my mind - means supporting  apt / dpkg, yum / dnf / rpm and ... msi? Nice for users of these package formats / package managers, but it still leaves people in the cold (pacman) and is a lot of new knowledge / work / maintenance on this side of the fence.

**Comment by sureshjoshi** [comment]
Ahh, fair point - I selfishly was only thinking about one of my workflows :)

**Comment by jsirois** [comment]
I won't object to a contribution of course. I personally won't devote time to learning 4 package formats and building this all out, but I will gladly review folks that want to contribute one or more.

**Comment by sureshjoshi** [comment]
Fair enough, that could be community run I suppose.

**Comment by kaos** [comment]
+1 for community supported packaging, and I'd be happy to contribute to the homebrew tap. (been having the same idea floating about but not yet surfacing..) :)

**Comment by jsirois** [comment]
That would be excellent then. Maybe you two could take that over.

**Comment by kaos** [comment]
Hmm... I'm not sure if this will be accepted into the core homebrew tap, due to this issue for new formulas:
```
* GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
```

It is easy enough to setup a custom tap, just slightly annoying when installing as it'll be more difficult to discover.

**Comment by kaos** [comment]
https://github.com/Homebrew/homebrew-core/pull/120557

**Comment by kaos** [comment]
As an example what that may look like, here's an small example tap: https://github.com/kaos/homebrew-shell

**Comment by jsirois** [comment]
Is there no support for pre built binaries? It's pretty atrocious to go through the completely un-necessary work of re-building a pre-built binary. The hash will even be the same ... it's literally burning the planet down for absolutely no purpose.

**Comment by kaos** [comment]
> Is there no support for pre built binaries? It's pretty atrocious to go through the completely un-necessary work of re-building a pre-built binary. The hash will even be the same ... it's literally burning the planet down for absolutely no purpose.

Ah, there is. That's the `cask` thing. I've always associated casks with "Apps", that is, mostly GUI applications, but what it really means is "install binary distribution".

I've created a cask for pants here: https://github.com/pantsbuild/homebrew-pants

@sureshjoshi please try it out see if it breaks/works for you. Seems to work for me. 

@jsirois Brew seems to be supported on linux too, if you're up for it, could see if this cask formula works on linux too? 😁  (if we'd rather find out if it doesn't work than an adventurous end-user..?)

**Comment by jsirois** [comment]
Says docker-man?!

**Comment by kaos** [comment]
Oh, I'm not touching docker at the moment... it's way to sluggish on ARM... :/

**Comment by kaos** [comment]
I may have to revisit once in a while in case there's been advancements, but a few months back it was a no-go perf wise.

**Comment by jsirois** [comment]
That's not what I mean. I don't use brew; so would not muddy my machine, I'd test it out in a container. You could do the same.

**Comment by kaos** [comment]
> That's not what I mean. I don't use brew; so I would not muddy my machine, I'd test it out in a container. You could do the same.

I got that. What I meant was that I'm not going to attempt run this in a container on an M1 right now, too painfully slow.

**Comment by jsirois** [comment]
Wow, ok. You Mac people are crazy!

**Comment by jsirois** [comment]
I'll try it out tonight when I get back to a keyboard.

**Comment by sureshjoshi** [comment]
Ha! Ooops :) 

```bash
 It seems there is already a Binary at '/usr/local/bin/pants'.
```

But, yes, it works!

```bash
⏺ ~/Desktop % brew install pantsbuild/pants/pants
==> Downloading https://github.com/pantsbuild/scie-pants/releases/download/v0.2.0/scie-pants-macos-x86_64
Already downloaded: /Users/sj/Library/Caches/Homebrew/downloads/bea575c6dc2edc4d3ece38ecd36120c7902cb7a10fe20fe613c2cd03dc9594f8--scie-pants-macos-x86_64
==> Installing Cask pants
==> Linking Binary 'scie-pants-macos-x86_64' to '/usr/local/bin/pants'
🍺  pants was successfully installed!
```

**Comment by kaos** [comment]
@jsirois thanks. just to be clear, it was an open question--meant mostly to highlight the possibility for this to be used on linux (and that I'm not going to explore that further)

**Comment by benjyw** [comment]
Closing this as completed. Thanks @kaos !
