### ISSUE TITLE
Exported shell functions create noise when running `pants`

### ISSUE THREAD

**Issue by danxmoran** [pantsbuild/scie-pants#63]
I define a utility functions in my `~/.bash_profile`, and `export -f` it:
```shell
function run_testdb () {
    docker run --rm -it \
        -e POSTGRES_HOST_AUTH_METHOD=trust \
        -e POSTGRES_DB=django \
        -e POSTGRES_USER=django_user \
        -p 5432:5432 \
        public.ecr.aws/docker/library/postgres:12 \
        -c max_locks_per_transaction=512 \
        -c fsync=false \
        -c synchronous_commit=off \
        -c full_page_writes=false \
        -c shared_buffers=256MB \
        -c autovacuum=off
}
export -f run_testdb
```

When I run the `scie-pants` binary in a shell after loading this profile, I see logs:
```
Could not interpret env entry run_testdb () . Skipping.
Could not interpret env entry { . Skipping.
Could not interpret env entry }. Skipping.
Could not interpret env entry run_testdb () . Skipping.
Could not interpret env entry { . Skipping.
Could not interpret env entry }. Skipping.
```

I'm not sure if it's possible to detect & silently skip exported functions (while preserving the log for non-functions). If not, it'd be nice to hide these behind some sort of "debug" logging option.

**Comment by danxmoran** [comment]
Looks like there's a `set` flag to have it omit functions from the output. Will set up a PR.

**Comment by danxmoran** [comment]
Ergh - `set -o posix` prevents functions from being printed as part of subsequent `set`s, but it also prevents newlines from being escaped in the values of vars like `IFS`, so it breaks the parser in a different way 🤔

**Comment by jsirois** [comment]
Yeah, and forcing posix mode would not be faithful to the current `source .pants.bootstrap` in the `./pants` script. I think that's a non-starter. I avoiding invoking /usr/bin/env since its another external assumed dependency. Current this has none - it only assumes bash and that's part and parcel of using `.pants.bootstrap` at all. I can take a quick look, but I think just adding a second binary to the crate that prints env vars is easy enough. I can have that ship in the scie and arrange bash to call it. Will also work on Windows.

**Comment by jsirois** [comment]
Right, that doesn't work since it only handles exported variables. As the current `./pants` sourcing arrangement stands, you need not export vars; you only need set them.

**Comment by danxmoran** [comment]
In this case it turns out the `export -f` isn't needed for my use-case (I thought it was for some reason - probably scarred from the days of running complex hacks in GNU `parallel`). So I'm ok closing this as a "won't do" if all the easy ideas are non-starters.

**Comment by jsirois** [comment]
This was a worthwhile find anyhow @danxmoran. I have a fix out for review.
